<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AcploUserRbac\Entity\UserRoleLinker'                     => __DIR__ . '/src/Entity/UserRoleLinker.php',
  'AcploUserRbac\Entity\UserRoleLinkerInterface'            => __DIR__ . '/src/Entity/UserRoleLinkerInterface.php',
  'AcploUserRbac\Factory\IdentityProviderFactory'           => __DIR__ . '/src/Factory/IdentityProviderFactory.php',
  'AcploUserRbac\Factory\IdentityRoleProviderFactory'       => __DIR__ . '/src/Factory/IdentityRoleProviderFactory.php',
  'AcploUserRbac\Factory\ModuleOptionsFactory'              => __DIR__ . '/src/Factory/ModuleOptionsFactory.php',
  'AcploUserRbac\Factory\SmartRedirectStrategyFactory'      => __DIR__ . '/src/Factory/SmartRedirectStrategyFactory.php',
  'AcploUserRbac\Factory\UserRoleLinkerMapperFactory'       => __DIR__ . '/src/Factory/UserRoleLinkerMapperFactory.php',
  'AcploUserRbac\Identity\IdentityProvider'                 => __DIR__ . '/src/Identity/IdentityProvider.php',
  'AcploUserRbac\Identity\IdentityRoleProvider'             => __DIR__ . '/src/Identity/IdentityRoleProvider.php',
  'AcploUserRbac\Identity\IdentityRoleProviderInterface'    => __DIR__ . '/src/Identity/IdentityRoleProviderInterface.php',
  'AcploUserRbac\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/Mapper/Exception/InvalidArgumentException.php',
  'AcploUserRbac\Mapper\UserRoleLinkerMapper'               => __DIR__ . '/src/Mapper/UserRoleLinkerMapper.php',
  'AcploUserRbac\Mapper\UserRoleLinkerMapperInterface'      => __DIR__ . '/src/Mapper/UserRoleLinkerMapperInterface.php',
  'AcploUserRbac\Module'                                    => __DIR__ . '/src/Module.php',
  'AcploUserRbac\Options\ModuleOptions'                     => __DIR__ . '/src/Options/ModuleOptions.php',
  'AcploUserRbac\Options\ModuleOptionsInterface'            => __DIR__ . '/src/Options/ModuleOptionsInterface.php',
  'AcploUserRbac\View\Strategy\SmartRedirectStrategy'       => __DIR__ . '/src/View/Strategy/SmartRedirectStrategy.php',
);
